In [3]:
import pandas as pd
import numpy as np
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [4]:
spss = pd.read_spss("./r25i_os_31.sav")

In [5]:
df = pd.DataFrame(spss)

In [6]:
df

,idind,uredid_i,uid_i,uid_h,tid_i,tid_h,sid_i,sid_h,rid_i,rid_h,...,um101,um102,um103,um104,um105,um106,um107,um108,um109,um111
0,3.00000,146901.00000,1001201.00000,10012.00000,1001201.00000,10012.00000,1001201.00000,10012.00000,1001201.00000,10012.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7.00000,147101.00000,1000301.00000,10003.00000,1000301.00000,10003.00000,1000301.00000,10003.00000,1000301.00000,10003.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9.00000,146801.00000,1000401.00000,10004.00000,1000401.00000,10004.00000,1000401.00000,10004.00000,1000401.00000,10004.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,36.00000,145501.00000,1002401.00000,10024.00000,1002401.00000,10024.00000,1002401.00000,10024.00000,1002401.00000,10024.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,37.00000,145502.00000,1002402.00000,10024.00000,1002402.00000,10024.00000,1002402.00000,10024.00000,1002402.00000,10024.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,39.00000,145504.00000,1002404.00000,10024.00000,nan,nan,nan,nan,1500704.00000,15007.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,60.00000,147902.00000,1004702.00000,10047.00000,nan,nan,1004702.00000,10047.00000,1004702.00000,10047.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,92.00000,139301.00000,1008401.00000,10084.00000,1008401.00000,10084.00000,1008401.00000,10084.00000,1008401.00000,10084.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,93.00000,139302.00000,1008402.00000,10084.00000,1008402.00000,10084.00000,1008402.00000,10084.00000,1008402.00000,10084.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,95.00000,139304.00000,1008404.00000,10084.00000,1008404.00000,10084.00000,1008404.00000,10084.00000,1008404.00000,10084.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,99.00000,139601.00000,1008501.00000,10085.00000,1008501.00000,10085.00000,1008501.00000,10085.00000,1008501.00000,10085.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,102.00000,281401.00000,1008601.00000,10086.00000,1008601.00000,10086.00000,1008601.00000,10086.00000,1008601.00000,10086.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,108.00000,281501.00000,1008801.00000,10088.00000,1008801.00000,10088.00000,1008801.00000,10088.00000,1008801.00000,10088.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,109.00000,281502.00000,1008802.00000,10088.00000,1008802.00000,10088.00000,1008802.00000,10088.00000,1008802.00000,10088.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,122.00000,139004.00000,1009204.00000,10092.00000,1009204.00000,10092.00000,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,125.00000,141601.00000,1010801.00000,10108.00000,1010801.00000,10108.00000,1010801.00000,10108.00000,1010801.00000,10108.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,126.00000,141602.00000,1010802.00000,10108.00000,1010802.00000,10108.00000,1010802.00000,10108.00000,1010802.00000,10108.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,135.00000,141901.00000,1011101.00000,10111.00000,1011101.00000,10111.00000,1011101.00000,10111.00000,1011101.00000,10111.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,136.00000,141902.00000,1011102.00000,10111.00000,1011102.00000,10111.00000,1011102.00000,10111.00000,1011102.00000,10111.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,141.00000,142402.00000,1011402.00000,10114.00000,1011402.00000,10114.00000,1011402.00000,10114.00000,1011402.00000,10114.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,160.00000,140801.00000,1013001.00000,10130.00000,1013001.00000,10130.00000,1013001.00000,10130.00000,1013001.00000,10130.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,170.00000,141001.00000,1013201.00000,10132.00000,1013201.00000,10132.00000,1013201.00000,10132.00000,1013201.00000,10132.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,171.00000,141002.00000,1013202.00000,10132.00000,nan,nan,1013202.00000,10132.00000,1013202.00000,10132.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,174.00000,141101.00000,1013401.00000,10134.00000,1013401.00000,10134.00000,1013401.00000,10134.00000,1013401.00000,10134.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,175.00000,141102.00000,1013402.00000,10134.00000,1013402.00000,10134.00000,1013402.00000,10134.00000,1013402.00000,10134.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,180.00000,143903.00000,1015603.00000,10156.00000,1015603.00000,10156.00000,1015603.00000,10156.00000,1015603.00000,10156.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,218.00000,282001.00000,1017301.00000,10173.00000,1017301.00000,10173.00000,1017301.00000,10173.00000,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,227.00000,282301.00000,1017601.00000,10176.00000,1017601.00000,10176.00000,1017601.00000,10176.00000,1017601.00000,10176.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,228.00000,282302.00000,1017602.00000,10176.00000,1017602.00000,10176.00000,1017602.00000,10176.00000,1017602.00000,10176.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,237.00000,143003.00000,1018903.00000,10189.00000,1018903.00000,10189.00000,1018903.00000,10189.00000,1018903.00000,10189.00000,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12524,54129.00000,397905.00000,1381171005.00000,13811710.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12525,54130.00000,107404.00000,1381215204.00000,13812152.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12526,54131.00000,21002.00000,1381220402.00000,13812204.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12527,54132.00000,667901.00000,1402396501.00000,14023965.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12528,54133.00000,667902.00000,1402396502.00000,14023965.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12529,54134.00000,667904.00000,1402396504.00000,14023965.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12530,54135.00000,667905.00000,1402396505.00000,14023965.00000,nan,nan,nan,nan,nan,nan,...,Нет,nan,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN
12531,54136.00000,667906.00000,1402396506.00000,14023965.00000,nan,nan,nan,nan,nan,nan,...,Нет,nan,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN
12532,54137.00000,487702.00000,1402398902.00000,14023989.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12533,54138.00000,107703.00000,1402402403.00000,14024024.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12534,54139.00000,107902.00000,1402413902.00000,14024139.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12535,54140.00000,108002.00000,1402419802.00000,14024198.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12536,54141.00000,108102.00000,1402421502.00000,14024215.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12537,54142.00000,108202.00000,1402422802.00000,14024228.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12538,54143.00000,108203.00000,1402422803.00000,14024228.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12539,54144.00000,108502.00000,1402426602.00000,14024266.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12540,54145.00000,668005.00000,1402439805.00000,14024398.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12541,54146.00000,108602.00000,1402444002.00000,14024440.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12542,54147.00000,487801.00000,1402445901.00000,14024459.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12543,54148.00000,487802.00000,1402445902.00000,14024459.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12544,54149.00000,487803.00000,1402445903.00000,14024459.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12545,54150.00000,668101.00000,1402446501.00000,14024465.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12546,54151.00000,668102.00000,1402446502.00000,14024465.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12547,54152.00000,668103.00000,1402446503.00000,14024465.00000,nan,nan,nan,nan,nan,nan,...,Нет,nan,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN
12548,54153.00000,668202.00000,1402452202.00000,14024522.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12549,54154.00000,668204.00000,1402452204.00000,14024522.00000,nan,nan,nan,nan,nan,nan,...,Нет,nan,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN
12550,54155.00000,668205.00000,1402452205.00000,14024522.00000,nan,nan,nan,nan,nan,nan,...,Нет,nan,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN
12551,54156.00000,668206.00000,1402452206.00000,14024522.00000,nan,nan,nan,nan,nan,nan,...,Нет,nan,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN
12552,54498.00000,489602.00000,138175102.00000,1381751.00000,nan,nan,nan,nan,nan,nan,...,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12553,58397.00000,643606.00000,136098906.00000,1360989.00000,136098906.00000,1360989.00000,nan,nan,nan,nan,...,Нет,nan,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN

In [7]:
df.describe()
edu_mar = df[['u_marst', 'u_educ']].dropna()

In [8]:
edu_mar

,u_marst,u_educ
0,Bдовец (вдова),10 и более классов школы и какое-либо професс....
1,Никогда в браке не состояли,7 классов школы
2,Состоите в зарегистрированном браке,1-2 года в высшем учебном заведении
3,Состоите в зарегистрированном браке,8 классов школы
4,Состоите в зарегистрированном браке,среднее образование - есть аттестат о ср. обра...
5,Разведены и в браке не состоите,10 и более классов школы и какое-либо професс....
6,Состоите в зарегистрированном браке,10 и более классов школы и какое-либо професс....
7,Состоите в зарегистрированном браке,10 и более классов школы и какое-либо професс....
8,Состоите в зарегистрированном браке,среднее образование - есть аттестат о ср. обра...
9,Bдовец (вдова),4 класса школы
10,Разведены и в браке не состоите,техникум с дипломом
11,Состоите в зарегистрированном браке,техникум с дипломом
12,Состоите в зарегистрированном браке,10 и более классов школы и какое-либо професс....
13,Состоите в зарегистрированном браке,8 классов школы
14,Разведены и в браке не состоите,есть диплом о высшем образовании
15,Состоите в зарегистрированном браке,среднее образование - есть аттестат о ср. обра...
16,Состоите в зарегистрированном браке,10 и более классов школы и какое-либо професс....
17,Состоите в зарегистрированном браке,10 и более классов школы и какое-либо професс....
18,Состоите в зарегистрированном браке,10 и более классов школы и какое-либо професс....
19,Bдовец (вдова),10 и более классов школы и какое-либо професс....
20,Bдовец (вдова),10 и более классов школы и какое-либо професс....
21,Состоите в зарегистрированном браке,техникум с дипломом
22,Состоите в зарегистрированном браке,10 и более классов школы и какое-либо професс....
23,Состоите в зарегистрированном браке,есть диплом о высшем образовании
24,Состоите в зарегистрированном браке,есть диплом о высшем образовании
25,Разведены и в браке не состоите,есть диплом о высшем образовании
26,Bдовец (вдова),техникум с дипломом
27,Состоите в зарегистрированном браке,8 классов школы
28,Состоите в зарегистрированном браке,8 классов школы
29,Никогда в браке не состояли,6 классов школы
...,...,...
12510,Состоите в зарегистрированном браке,есть диплом о высшем образовании
12512,Разведены и в браке не состоите,техникум с дипломом
12513,Состоите в зарегистрированном браке,есть диплом о высшем образовании
12514,Состоите в зарегистрированном браке,9 классов школы
12516,Состоите в зарегистрированном браке,техникум с дипломом
12519,Состоите в зарегистрированном браке,есть диплом о высшем образовании
12523,"Живете вместе, но не зарегистрированы",техникум с дипломом
12524,"Живете вместе, но не зарегистрированы",техникум с дипломом
12525,Никогда в браке не состояли,есть диплом о высшем образовании
12526,Никогда в браке не состояли,есть диплом о высшем образовании
12527,Состоите в зарегистрированном браке,техникум с дипломом
12528,Состоите в зарегистрированном браке,среднее образование - есть аттестат о ср. обра...
12529,Никогда в браке не состояли,8 классов школы
12532,Состоите в зарегистрированном браке,1-2 года в высшем учебном заведении
12533,"ОФИЦИАЛЬНО ЗАРЕГИСТРИРОВАНЫ, НО ВМЕСТЕ НЕ ПРОЖ...",есть диплом о высшем образовании
12534,Состоите в зарегистрированном браке,техникум с дипломом
12535,Состоите в зарегистрированном браке,среднее образование - есть аттестат о ср. обра...
12536,Состоите в зарегистрированном браке,есть диплом о высшем образовании
12537,Состоите в зарегистрированном браке,есть диплом о высшем образовании
12538,Никогда в браке не состояли,9 классов школы
12539,Состоите в зарегистрированном браке,3 и более лет в высшем учебном заведении
12540,Состоите в зарегистрированном браке,10 и более классов школы и какое-либо професс....
12541,Состоите в зарегистрированном браке,техникум с дипломом
12542,Состоите в зарегистрированном браке,есть диплом о высшем образовании
12543,Состоите в зарегистрированном браке,есть диплом о высшем образовании
12544,Никогда в браке не состояли,есть диплом о высшем образовании
12545,Никогда в браке не состояли,3 и более лет в высшем учебном заведении
12546,Разведены и в браке не состоите,есть диплом о высшем образовании
12548,"Живете вместе, но не зарегистрированы",10 и более классов школы и техникум без диплома
12552,Состоите в зарегистрированном браке,есть диплом о высшем образовании

In [27]:
def filter_rows(df, column_name, value):
    return df[df[column_name] != value]
def show_categories(df, column_name):
    d = {x : len(df[df[column_name] == x]) for x in list(df[column_name].dtype.categories)}
    d.update({'Всего' : len(df)})
    return d
def replace_categories(df, column_name, replacesments: dict):
    for k,v in replacesments.items():
        df[df[column_name] == k] = v
    return df

In [10]:
df_formatted = filter_rows(edu_mar, 'u_marst', 'ЗАТРУДНЯЮСЬ ОТВЕТИТЬ')
df_formatted = filter_rows(df_formatted, 'u_marst', 'НЕТ ОТВЕТА')
df_formatted = filter_rows(df_formatted, 'u_marst', 'ОТКАЗ ОТ ОТВЕТА')

In [34]:
print(len(df[df['u_marst'] == 'Состоите в зарегистрированном браке']))
df_formatted['u_marst'].dtype.categories[0]

SyntaxError: invalid syntax (<ipython-input-34-eaaf80afb2b0>, line 3)

In [16]:
show_categories(df_formatted, 'u_marst')

{'Bдовец (вдова)': 1457,
 'Живете вместе, но не зарегистрированы': 1018,
 'ЗАТРУДНЯЮСЬ ОТВЕТИТЬ': 0,
 'НЕТ ОТВЕТА': 0,
 'Никогда в браке не состояли': 2005,
 'ОТКАЗ ОТ ОТВЕТА': 0,
 'ОФИЦИАЛЬНО ЗАРЕГИСТРИРОВАНЫ, НО ВМЕСТЕ НЕ ПРОЖИВАЮТ': 44,
 'Разведены и в браке не состоите': 868,
 'Состоите в зарегистрированном браке': 5218,
 'Всего': 10610}

In [28]:
replace_categories(df_formatted, 'u_marst', {'Состоите в зарегистрированном браке' : 1})

ValueError: Cannot setitem on a Categorical with a new category, set the categories first